class BreakFailureException(AssertionError):
    ROBOT_CONTINUE_ON_FAILURE = False
    pass
