class FailureException(Exception):
    ROBOT_CONTINUE_ON_FAILURE = True
    pass
