class FailureException():
    ROBOT_CONTINUE_ON_FAILURE = True
    pass
